name: Android APK (Debug)

on:
  workflow_dispatch:
  push:
    branches: ["main", "master"]

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Gradle 8.2.1
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: "8.2.1"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Debug APK
        run: gradle :app:assembleDebug --stacktrace

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: KaloriBelTounsi-debug-apk
          path: app/build/outputs/apk/debug/*.apk
